import Head from 'next/head'
import { Layout } from '@/components/Layout/Layout'

export default function Home() {
  return (
    <div className='bg-black text-white'>
      <Head>
        <title>Nanite Systems</title>
        <meta name="Nanite Systems" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Orbitron&family=Tomorrow&display=swap" rel="stylesheet"></link>
      </Head>

      <Layout />

    </div>
  )
}